apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: ghcr.io/lucas-everaerts/my-app:5cd84e45935e1f283476085d12eb78a0ea1b2f47
          ports:
            - containerPort: 5000