apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: ghcr.io/lucas-everaerts/my-app:3f25cd5f70bb65e5adcd6e4ed87fca6fe405303c
          ports:
            - containerPort: 5000