apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: ghcr.io/lucas-everaerts/my-app:e8dd2365520228d603ab61d15e4134713a6b0f06
          ports:
            - containerPort: 5000